" vimrc of Thomas Witt <http://github.com/thomaswitt>

set shell=/usr/bin/env\ bash
set shellcmdflag=-l\ -c

language messages en_US.UTF-8

" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" ¿ then run :PlugInstall
call plug#begin()
Plug 'junegunn/vim-easy-align'
  "Plug 'garbas/vim-snipmate'      " TextMate-style snippets for Vim
  Plug 'AndrewRadev/switch.vim'   " Switch segments of text predefined repls
  Plug 'artnez/vim-wipeout'       " Destroy all buffers that are not open
  Plug 'ctrlpvim/ctrlp.vim'       " Fuzzy Search
  Plug 'dense-analysis/ale'       " Check/fix syntax asynchronously
  Plug 'github/copilot.vim'       " Github Copilot
  Plug 'jlanzarotta/bufexplorer'
  Plug 'preservim/nerdtree' | Plug 'Xuyuanp/nerdtree-git-plugin' " Filetree
  "Plug 'ruby-formatter/rufo-vim'  " RuFo
  Plug 'stefanoverna/vim-i18n'    " Rails Translations
  Plug 'tomasr/molokai'           " TextMate Colorscheme
  Plug 'tomtom/tcomment_vim'      " comment vim-plugin
  Plug 'tpope/vim-endwise'        " Ruby on Rails
  Plug 'tpope/vim-fugitive'       " git
  Plug 'tpope/vim-rails'          " Ruby on Rails
  Plug 'tpope/vim-rbenv'          " RBenv
  Plug 'tpope/vim-repeat'         " enable repeat supported plugin maps with .
  Plug 'tpope/vim-sensible'       " Sensible defaults
  Plug 'tpope/vim-surround'       " quoting/parenthesizing made simple
  Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes' "Status
  Plug 'vim-ruby/vim-ruby'        " Vim/Ruby Configuration Files
  Plug 'vim-scripts/BufOnly.vim'  " Delete all the buffers except the current
  Plug 'rking/ag.vim'             " Use ag, the_silver_searcher
  Plug 'vim-scripts/greplace.vim' " Global replace
call plug#end()

set autoindent          " Always set autoindenting on
set cmdheight=2         " Height of the command line, avoid hit enter prompts
set confirm             " Use confirmation dialogs
set directory=~/.vimbackup,.,~/tmp,/var/tmp,/tmp
set encoding=utf-8      " The terminal encoding
set expandtab           " Use the appropriate number of spaces to insert a <Tab>
set formatoptions=ctqrlj  " wrap comts/text, gq, cont. comments, keep long lines
set hidden              " Allow several buffers to be opened (and unsaved)
set hlsearch                          " Highlight search results
set ignorecase          " Case-insensitive search by default
set list                " List mode:Show tabs as CTRL-I, show end of line with $
set modeline            " Read vim configuration from inside loaded files
set modelines=5         " Scan up to 5 lines for a modeline
set nostartofline       " Don't move the cursor to the first non blank char
set report=0            " Always report number of lines changed
set scrolloff=4         " Minimal number of lines above and below the cursor
set shiftwidth=2        " Number of spaces to use for each step of (auto)indent
set showcmd             " Show (partial) command in the last line of the screen
set showmatch           " Highlight matching brackets
set smartcase           " Respect case if the pattern contains upper case chars
set softtabstop=2       " Number of spaces that a <Tab> counts
set tabstop=2           " Number of spaces that a <Tab> in the file counts for
set textwidth=72        " Textwidth 72 chars
set title               " Set/change the window title
set viminfo=%,'500,<500,:5000,/500,@500 " viminfo: files, reg, cmds, sea, hist
set visualbell          " Use visual bell instead of a sound
set whichwrap=<,>,[,]   " dont wrap at these special movements
set wildignore+=.git    " Ignore .git repositories
set wildmode=list:longest,list:full     " Completion mode
set wrap                " Display long lines wrapped

" Powerline Fonts
" let g:airline_powerline_fonts = 1

autocmd FileType * set ts=2 sts=2 sw=2 expandtab

" Search for the string marked in visual mode. E.g.: press v, go some chars to the right, press /
vmap / y/<C-R>"<CR>
vmap ß y:Ack "<C-R>""<CR>

" Don't use Ex mode, use Q for formatting
map Q gq

" Ctrl-p: previous buffer
"map <C-p> :bp<CR>

" Ctrl-n: next buffer
"map <C-n> :bn<CR>

" Go over wrapped lines with j and k. These will jump to the next/previous
" displayed line instead of the next/previous physical line.
map j gj
map k gk

" Change single- to doublequotes and vice versa (requires surround plugin)
nmap ,' cs"'
nmap ," cs'"

" VSplit
map ,vs :vsplit<CR>

" Strip Returns
map ,cel :%s/^\n//<CR>

" Strip Whitespaces
map ,sws :%s/\s\+$//<CR>

" F1: Run Rake
map <F1> :Rake<CR>

" Shift-F1: GitX
map <S-F1> :!open -a GitX .<CR>

" F2: Select all.
nnoremap <F2> ggVG
nnoremap <S-F2> ggVG"+y

" F3: Toggle line wrapping
nnoremap <F3> :set wrap!<CR>

" F4: Toggle paste mode.
nnoremap \pt :set invpaste paste?<CR>
nmap <F4> \pt
imap <F4> <C-O>\pt
set pastetoggle=<F4>

" F5: Toggle line numbering.
nmap <silent> <F5> :set invnumber<CR>

" F6: Copilot
map <F6> :Copilot enable<CR>
map <S-F6> :Copilot disable<CR>

" F7: ALE
nnoremap <F7> :ALEToggle<CR>

" F8: none
" map <F8> :set buftype=nofile<CR>
" map <S-F8> :set buftype=<CR>

" F9: Current Buffer will not be written (for templfiles)
nnoremap <silent> <F9> :NERDTreeToggle<CR>

" F10: Buffer Explorer / Delete Buffers
nnoremap <silent> <F10> :BufExplorer<CR>

" F11: Wipeout/BufOnly
nnoremap <silent> <F11> :Wipeout!<CR>
nnoremap <silent> <S-F11> :BufOnly!<CR>

" F12: Rails find
nnoremap <silent> <F12> :Rfind

" Tabs
nnoremap <D-M-Left> gT
nnoremap <D-M-Right> gt

" Remap []{}|\~ on the mac for easier typing on the Mac
map! <D-ü> [
map! <D-+> ]
map! <D-Ü> {
map! <D-*> }
map! <D-°> ~
map! <D-Ä> \
map! <D-'> \|

" RGrep
:let Grep_Find_Use_Xargs = 0

if exists('$ITERM_PROFILE')
  if exists('$TMUX')
    let &t_SI = "\<Esc>[3 q"
    let &t_EI = "\<Esc>[0 q"
  else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
  endif
end

" For tmux to automatically set paste and nopaste mode at the time pasting (as
" happens in VIM UI)

function! WrapForTmux(s)
  if !exists('$TMUX')
    return a:s
  endif
  let tmux_start = "\<Esc>Ptmux;"
  let tmux_end = "\<Esc>\\"
  return tmux_start . substitute(a:s, "\<Esc>", "\<Esc>\<Esc>", 'g') . tmux_end
endfunction

let &t_SI .= WrapForTmux("\<Esc>[?2004h")
let &t_EI .= WrapForTmux("\<Esc>[?2004l")

" Enable rufo (RUby FOrmat)
let g:rufo_auto_formatting = 1

" ALE
let g:ale_ruby_rufo_executable = '/Users/thomas/.rbenv/shims/rufo'
let g:ale_ruby_rubocop_executable = '/Users/thomas/.rbenv/shims/rubocop'
let g:ale_eruby_erblint_executable = '/Users/thomas/.rbenv/shims/erblint'
let g:ale_linters = {
\ 'ruby': ['rubocop'],
\ 'eruby': ['erblint'],
\}
let g:ale_linters_explicit = 1
let g:ale_sign_column_always = 1
" let g:ale_sign_error = '\u2022'
" let g:ale_sign_warning = '\u2022'

" Github Copilot
let g:copilot_node_command = "/opt/homebrew/bin/node"

" Disable Copilot by default
let g:copilot_enabled = v:false
let g:copilot_filetypes = {
  \ '*': v:false,
  \ 'css': v:true,
  \ 'html': v:true,
  \ 'ruby': v:true,
  \ 'eruby': v:true,
  \ 'sass': v:true,
  \ 'scss': v:true,
\ }

autocmd BufReadPre *
   \ let f=getfsize(expand("<afile>"))
   \ | if f > 100000 || f == -2
   \ | let b:copilot_enabled = v:false
   \ | endif

" augroup DeleteTrailingWhitespaces
"   autocmd!
"   autocmd BufWritePre * :%s/\s\+$//e
" augroup END

" augroup Go
"   autocmd! FileType go  setlocal tabstop=4 shiftwidth=4 softtabstop=4 noexpandtab nolist
"   let g:go_fmt_command = "goimports"
"   " Show type info for the word under your cursor:
"   au FileType go nmap <Leader>i <Plug>(go-info)
"   au FileType go nmap <leader>r <Plug>(go-run)
"   " au FileType go nmap <leader>b <Plug>(go-build)
"   au FileType go nmap <leader>t <Plug>(go-test)
"   au FileType go nmap <leader>c <Plug>(go-coverage)
"   au FileType go nmap <Leader>e <Plug>(go-rename)
"   au FileType go nmap <leader>l :GoLint<CR>
"   au FileType go nmap gd <Plug>(go-def)
"   autocmd BufWritePost *.go GoLint
" augroup END

if has("gui_running")                   " GUI running?
  set guifont=Inconsolata-dz:h16        " Bigger font for MacVim
  set antialias                         " Anti Aliased Font
  winsize 80 80                         " Resize Window
  set guioptions-=m                     " Remove menu bar
  set guioptions-=T                     " Remove toolbar
  set background=dark
  colorscheme molokai
endif

" Call vim via VIM_PRIVATE=1 vim for privacy
if $VIM_PRIVATE
  set history=0
  set nobackup
  set nomodeline
  set noshelltemp
  set noswapfile
  set noundofile
  set nowritebackup
  set secure
  set viminfo=""
  let g:copilot_filetypes = { '*': v:false, }
  let b:copilot_enabled = { v:false }
endif
